/*
Copyright © 2025 NAME HERE <EMAIL ADDRESS>
*/
package cmd

import (
	"dotfiles/internal"
	"os"
	"path"

	"github.com/spf13/cobra"
)

// hookCmd represents the hook command
var hookCmd = &cobra.Command{
	Use:   "hook",
	Short: "A brief description of your command",
	Long: `A longer description that spans multiple lines and likely contains examples
and usage of using your command. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.`,
	Run: func(cmd *cobra.Command, args []string) {
		root, _ := cmd.Flags().GetString("root")
		dataDir := internal.DefaultDataDir()
		if root != "" {
			dataDir = path.Join(root, "data")
		}
		hookLines := []string{
			"# Generated by dotfiles hook command",
		}
		// Source shell hooks from dataDir/shell/*.sh
		shellHookDir := path.Join(dataDir, "shell")
		hookFile := path.Join(shellHookDir, "hook.sh")
		hookLines = append(hookLines, "export DOTFILES_DATA_DIR=\""+dataDir+"\"")
		hookLines = append(hookLines, "if [ -f \""+hookFile+"\" ]; then")
		hookLines = append(hookLines, "  . \""+hookFile+"\"")
		hookLines = append(hookLines, "fi")

		for _, line := range hookLines {
			os.Stdout.WriteString(line + "\n")
		}

	},
}

func init() {
	rootCmd.AddCommand(hookCmd)

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// hookCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	// hookCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}
