/*
Copyright © 2025 NAME HERE <EMAIL ADDRESS>
*/
package cmd

import (
	"dotfiles/internal"
	"os"
	"path"

	"github.com/spf13/cobra"
)

// hookCmd represents the hook command
var hookCmd = &cobra.Command{
	Use:   "hook",
	Short: "A shell hook for aliases, etc.",
	Long:  `Generates shell code to be sourced in order to set up aliases and environment variables for the dotfiles manager.`,
	Run: func(cmd *cobra.Command, args []string) {
		root, _ := cmd.Flags().GetString("root")
		dataDir := internal.DefaultDataDir()
		if root != "" {
			dataDir = path.Join(root, "data")
		}
		hookLines := []string{
			"# Generated by dotfiles hook command",
		}
		// Source shell hooks from dataDir/shell/*.sh
		shellHookDir := path.Join(dataDir, "shell")
		hookFile := path.Join(shellHookDir, "hook.sh")
		hookLines = append(hookLines, "export DOTFILES_DATA_DIR=\""+dataDir+"\"")
		hookLines = append(hookLines, "if [ -f \""+hookFile+"\" ]; then")
		hookLines = append(hookLines, "  . \""+hookFile+"\"")
		hookLines = append(hookLines, "fi")

		for _, line := range hookLines {
			os.Stdout.WriteString(line + "\n")
		}

	},
}

func init() {
	rootCmd.AddCommand(hookCmd)
}
